
export const api = {
  PUBLIC_BLOG_CATEGORY_LIST: "/api/blog/category",
  PUBLIC_BLOG_CONTENT_LIST: "/api/blog/content",
  PUBLIC_BLOG_COMMENT_LIST: "/api/blog/comment",
  PUBLIC_BLOG_COMMENT_STORE: "/api/blog/comment/store",
  DASHBOARD_BLOG_CONTENT_LIST: "/api/dashboard/blog/content",
  DASHBOARD_BLOG_CONTENT_CREATE: "/api/dashboard/blog/content/create",
  DASHBOARD_BLOG_CONTENT_UPDATE: "/api/dashboard/blog/content/update",
  DASHBOARD_BLOG_CONTENT_DELETE: "/api/dashboard/blog/content/delete",
  DASHBOARD_BLOG_CATEGORY_LIST: "/api/dashboard/blog/category",
  DASHBOARD_BLOG_CATEGORY_CREATE: "/api/dashboard/blog/category/create",
  DASHBOARD_BLOG_CATEGORY_UPDATE: "/api/dashboard/blog/category/update",
  DASHBOARD_BLOG_CATEGORY_DELETE: "/api/dashboard/blog/category/delete",
  DASHBOARD_BLOG_TAG_LIST: "/api/dashboard/blog/tag",
  DASHBOARD_BLOG_TAG_CREATE: "/api/dashboard/blog/tag/create",
  DASHBOARD_BLOG_TAG_UPDATE: "/api/dashboard/blog/tag/update",
  DASHBOARD_BLOG_TAG_DELETE: "/api/dashboard/blog/tag/delete",
  DASHBOARD_BLOG_COMMENT_LIST: "/api/dashboard/blog/comment",
  DASHBOARD_BLOG_COMMENT_DELETE: "/api/dashboard/blog/comment/delete",
}